#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: rkratky/documentation-workflows/.github/workflows/documentation-checks.yaml@spellcheck
    with:
      working-directory: "docs"
      fetch-depth: 0
