name: Automatic documentation checks

on:
  push:
    branches: [ main ]

jobs:
  docchecks:
    name: Run documentation checks
    runs-on: ["ubuntu-24.04"]
    outputs:
      result_spelling: ${{ steps.spellcheck-step.outcome }}
      # result_pa11y: ${{ steps.pa11y-step.outcome }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Spell Check
        id: spellcheck-step
        if: success() || failure()
        uses: hloeung/documentation-workflows/spellcheck@main
        with:
          working-directory: 'docs'
          install-target: 'install'
          spelling-target: 'spelling'
          makefile: 'use-default'
